# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: BioJS UniProt Protein Features Viewer
email: ljgarcia|xwatkins@ebi.ac.uk
description: A BioJS viewer for protein sequence features
encoding: utf-8
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: uniprot
github_username:  ebi-uniprot

# Build settings
markdown: kramdown
kramdown:
  input: GFM
exclude: [build/, coverage/, documentation/, hands-on/, lib/, node_modules/, reports/, snippets/]
